---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry
spec:
  secretName: docker-registry-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  isCA: false
  commonName: registry.k3s.l4b.space
  dnsNames:
    - registry.k3s.l4b.space
