all:
  hosts:
    1-single-dev.node.k3s:
      ansible_host: k3s.l4b.space
      ansible_user: root
      ansible_port: 22
      cluster_config_filepath: /tmp/k3s.l4b.space.yml
      cert_manager_namespace: cert-manager
      cert_manager_version: v1.2.0
  children:
    k3s:
      hosts:
        1-single-dev.node.k3s:
